# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma9SMqa3zKyQE9kidq2qBaO4ZduQIKKL
"""

import streamlit as st
import pandas as pd
import random

# Configuración de la página
st.set_page_config(page_title="Menú Familiar Quitian", layout="wide")

st.title("🥑 Planificador de Menús - Familia Quitian")
st.write("Planificación para: 2 Adultos, Niño (2 años), Bebé (6 meses)")

# 1. Cargar Datos (Simulando la carga de tu archivo)
# En tu caso real usarás: df = pd.read_excel("ALIMENTACION.xlsx")
# Aquí creo un dataframe con tus datos de muestra para que el código sea ejecutable ya mismo.
data = {
    'VERDURA': ['AGUACATE', 'BROCOLI COCIDO', 'REMOLACHA', 'ZANAHORIA', 'TOMATE', 'COLIFLOR COCIDO', 'ENSALADA MIXTA'],
    'PROTEINA': ['PECHUGA DESMECHADA', 'HUEVO COCIDO', 'CARNE MOLIDA', 'PESCADO', 'CERDO ASADO', 'ALBONDIGAS', 'HAMBURGUESAS'],
    'CARBOHIDRATOS': ['PAPA COCIDA', 'ARROZ', 'PASTAS', 'PLATANO AMARILLO', 'AREPA DE YUCA', 'PAPA CRIOLLA', 'PATACONES'],
    'NIÑOS_RECETAS': ['PANCAKES DE MANZANA', 'TORTILLA DE PAPA', 'PURE DE MANZANA', 'MUFFINS DE ARANDANO', 'MONEDITAS DE PAPA', 'HELADO DE KIWI', 'NUGGETS DE QUINUA'],
    'FRUTA': ['PAPAYA', 'BANANO', 'MANDARINA', 'MANZANA', 'PERA', 'KIWI', 'FRESAS']
}

# Normalizar longitudes para el dataframe de ejemplo
max_len = max(len(v) for v in data.values())
for k in data:
    data[k] += [None] * (max_len - len(data[k]))

df = pd.DataFrame(data)

# 2. Lógica de Generación
def generar_menu():
    dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
    menu = []

    # Limpiar NaNs
    proteinas = df['PROTEINA'].dropna().tolist()
    carbos = df['CARBOHIDRATOS'].dropna().tolist()
    verduras = df['VERDURA'].dropna().tolist()
    ninos = df['NIÑOS_RECETAS'].dropna().tolist()
    frutas = df['FRUTA'].dropna().tolist()

    for dia in dias:
        row = {
            'Día': dia,
            'Proteína': random.choice(proteinas),
            'Carbohidrato': random.choice(carbos),
            'Verdura': random.choice(verduras),
            'Lonchera/Niño': random.choice(ninos),
            'Fruta/Postre': random.choice(frutas),
            'Tip Bebé 6m': 'Ofrecer ingrediente aislado: ' + random.choice([random.choice(verduras), random.choice(frutas)])
        }
        menu.append(row)

    return pd.DataFrame(menu)

# 3. Interfaz de Usuario
if st.button('🔄 Generar Nuevo Menú Semanal'):
    menu_semanal = generar_menu()
    st.session_state['menu'] = menu_semanal

if 'menu' in st.session_state:
    st.dataframe(st.session_state['menu'], use_container_width=True)

    st.subheader("📝 Lista de Compras Sugerida")
    col1, col2 = st.columns(2)
    with col1:
        st.write("**Proteínas:**")
        st.write(", ".join(set(st.session_state['menu']['Proteína'])))
    with col2:
        st.write("**Verduras y Frutas:**")
        st.write(", ".join(set(st.session_state['menu']['Verdura']).union(set(st.session_state['menu']['Fruta/Postre']))))

else:
    st.info("Haz clic en el botón para generar tu primer menú.")

st.markdown("---")
st.caption("Nota: Para el bebé de 6 meses, recuerda ofrecer los alimentos sin sal, sin azúcar y en texturas seguras (BLW o Papilla).")